config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :users
  root "home#top"
  get "home/about"=>"home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body,  presence: true
	validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books,dependent: :destroy
  attachment :profile_image
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
     root_path 
  end
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :before_book ,only: [:edit]

	def index
		@books=Book.all
		@book=Book.new
		@user=current_user
	end

	def new
		@book=Book.new
	end

	def show
		@book=Book.find(params[:id])
		@new_book = Book.new
		@user=Book.find(params[:id]).user
	end

	def before_book
		@book=Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end

	def edit
		@book=Book.find(params[:id])
	end

	def create
		@book=Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
       	flash[:create]="You have creatad book successfully."
		redirect_to book_path(@book.id)
       	else
       		@books=Book.all
       		render "books/index"
	end
	end

	def update
		@book=Book.find(params[:id])
		if @book.update(book_params)
			flash[:update]="You have updated book successfully."
		redirect_to book_path(@book.id)
	    else
	    	render "books/edit"
	end
	end

	def destroy
		@book=Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title ,:body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :before_edit ,only: [:edit]

	def index
		@book=Book.new
		@users=User.all
	end

	def show
		@book=Book.new
		@user=User.find(params[:id])
		@books=User.find(params[:id]).books
	end

	def new
		@book=Book.new
	end

	def before_edit
		@user=User.find(params[:id])
		if @user.id != current_user.id
			redirect_to user_path(current_user.id)
		end
	end

	def edit
		@user=User.find(params[:id])
	end


	def update
		@user=User.find(params[:id])
		if @user.update(user_params)
		flash[:update]="You have updated user successfully."
		redirect_to user_path(current_user.id)
		else
		render "users/edit"
	end
	end

	private

	def user_params
		params.require(:user).permit(:name,:profile_image,:introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
      	<div class="col-lg-4">
      		<% if flash[:notice]%>
			 <p class="flash-txt"><%= flash[:notice] %></p>
			<% end %>






			<h2>user info</h2>
			<%= attachment_image_tag user, :profile_image, :fill,100,100,format:"jpeg",fallback: "no_image.jpg"  %><br>
			<span>name</span>
			<%= user.name %><br>
			<sapn>introduction</sapn>
			<%= user.introduction %><br>
			<%= link_to edit_user_path(user) do %>
			<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
			<% end %>

			<h2>New book</h2>
			<%= form_for(book,url: '/book') do |f| %>
			 <p>Title</p>
			 <%= f.text_field :title %>
			 <p>Body</p>
			 <%= f.text_area :body %><br>
			 <%= f.submit do %>
			 <button type="button" class="btn btn-success">Crete Book</button>
			 <% end %>
			 <% end %>
		</div>

app/views/books/create.html.erb
<h1>Books</h1>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
   <p class=" error-title">2 errors prohibited this book from being saved:</p>
   <ul>
     <li>book can't be blank</li>
     <li>title is too short (minimum is 2 characters)</li>
   </ul>
 <% end %>


<h2>Editing Book</h2><br><br>

<%= form_for(@book) do |f| %>

<p>title</p>
<%= f.text_field :title %>

<p>body</p>
<%= f.text_area :body %><br>

<%= f.submit 'Update Book' %>
<% end %>

<%= link_to "Show" ,book_path(@book.id)%>
<%= link_to "Back" ,books_path %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
   <p class=" error-title">2 errors prohibited this book from being saved:</p>
   <ul>
     <li>book can't be blank</li>
     <li>title is too short (minimum is 2 characters)</li>
   </ul>
 <% end %>

<%= flash[:notice] %>

<%= render"/users/list",user: current_user ,book:@book %>

<div class='col-xs-9'>
    <h2>Books</h2>
 <table class='table table-hover table-inverse'>
	<tr><td></td><td>Title</td><td>Opinion</td><td></td></tr>
	<% @books.each do |book| %>
	<tr>
		<td><%= link_to attachment_image_tag(book.user, :profile_image, :fill,40,40,format:"jpeg",fallback: "no_image.jpg"),user_path(book.user.id)  %></td>
		<td><%= link_to (book.title), book_path(book.id)%></td>
		<td><%= book.body %></td>
	</tr>
	<% end %>
</table>
</div>

app/views/books/new.html.erb
<div class="container">
      <div class="row">

<%= render 'book/list' %>

			<div class="col-lg-8">
			<h2>Users</h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>title</th><th>opinion</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
		

app/views/books/show.html.erb
<% if flash[:update]%>
   <p class="flash-txt"><%= flash[:update] %></p>
  <% end %>

<%= render"/users/list",user:@user,book:@new_book %>

<div class='col-xs-9'>
<h1>Book detail</h1>
<table class="table table-striped">
	<tr><td></td><td></td><td></td><td></td><td></td></tr>
	<tr>
		<td><%= link_to(user_path(@book.user.id)) do %>
			<%= attachment_image_tag(@user,:profile_image, :fill,50,50,format:"jpeg",fallback: "no_image.jpg") %>
			<%= @book.user.name%>
			<% end %>
		</td>
		<td><%= @book.title %></td>
		<td><%= @book.body %></td>

		<% if @book.user_id == current_user.id %>
		<td><%= link_to "Edit",edit_book_path(@book.id) %></td>
		<td><%= link_to"Destroy",book_path(@book.id), method: :delete ,data:{confirm:"Are you sure?"} %>
		</td>
		<% end %>
	</tr>
</table>
</div>

app/views/home/about.html.erb
<h1>about</h1>

app/views/home/top.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<h1>top</h1>

<p>welcome bookers</p>


<div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <nav class='nav navbar-nav navbar-left' >
        <span>Bookers</span>
      </nav>
      <nav>
      <div calss="header_navi">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to "home",user_path(current_user.id)%></li>
          <li><%= link_to "Users",users_path %></li>
          <li><%= link_to "books",books_path %></li>
          <li><%= link_to "logout",destroy_user_session_path,method: :delete%></li>
          <% else %>
          <li><%= link_to "home" ,root_path %></li>
          <li><%= link_to "about",home_about_path %></li>
          <li><%= link_to "sign up",new_user_registration_path %></li>
          <li><%= link_to "login",new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </nav>
</div>
</header>

<div class='body'>
   <div class='container'>
        <div class='row'>
        <%= yield %>
      </div>
   </div>
</div>

<footer>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/users/_list.html.erb
 <div class='col-xs-3'>
 	
 	<% if flash[:create]%>
   <p class="flash-txt"><%= flash[:create] %></p>
  <% end %>

  <% if flash[:upadte]%>
   <p class="flash-txt"><%= flash[:update] %></p>
  <% end %>

<h2>User info</h2>
<table class='table'>
	<tr><%= attachment_image_tag user, :profile_image, :fill,100,100,format:"jpeg",fallback: "no_image.jpg"  %></tr>
	<tr>
	   <th>name</th>
	   <th><%= user.name %></th>
	</tr>
	<tr>
	   <th>introduction</th>
	   <th><%= user.introduction %></th>
	</tr>
</table>


<% if user.id == current_user.id %>
<div class='row'>
  	<%= link_to "edit",edit_user_path(current_user.id) %>
</div>
<% else %>
<div class='row'>
  	<%= link_to "edit",user_path(user.id) %>
</div>
<% end %>

<h2>New book</h2>
<%= form_for(book) do |f|%>
<p>title</p>
<%= f.text_field :title %>
<p>Opinion</p>
<%= f.text_area :body %>
<div class="actions row"><%= f.submit %></div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="edit_page">



<h2>User info</h2>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
   <p class=" error-title">2 errors prohibited this book from being saved:</p>
   <ul>
     <li>name can't be blank</li>
     <li>introduction is too short (minimum is 2 characters)</li>
   </ul>
 <% end %>
<p>name</p>
<%= f.text_field :name %>

<p>photo</p>
<%= f.attachment_field :profile_image %>

<p>introduction</p>
<%= f.text_area :introduction %>
<%= f.submit %>
<% end %>

</div>

app/views/users/index.html.erb
<% if @book.errors.any? %>
   <p>2 errors prohibited this obj from being saved:
Title can't be blank
Body can't be blank</p>
<% end %>

<%= render"users/list",user:current_user ,book:@book %>

<div class='col-xs-9'>
<h1>Users</h1>
<div class="container"> <!-- ここを追加 -->
      <div class="row"> 
      <div class="col-lg-8">   <!-- ここを追加 -->
<table class="table table-striped">
	<tr><td>image</td><td>name</td><td></td></tr>
	<tr><% @users.each do |user| %>
		<td><%= attachment_image_tag user , :profile_image, :fill,45,45,format:"jpeg",fallback: "no_image.jpg" %></td>
		<td><%= user.name %></td>
		<td><%= link_to "Show",user_path(user.id)%></td>
	</tr>
	<% end %>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<% if flash[:create]%>
   <p class="flash-txt"><%= flash[:create] %></p>
  <% end %>

<% if flash[:update]%>
   <p class="flash-txt"><%= flash[:update] %></p>
  <% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<% if @user.errors.any? %>
  <div class="error-box">
   <p class=" error-title">2 errors prohibited this book from being saved:</p>
   <ul>
     <li>Name can't be blank</li>
     <li>Name is too short (minimum is 2 characters)</li>
   </ul>
   </div>
 <% end %>

<%= render"users/list",user:current_user,book:@book %>


<div class='col-xs-9'>
    <h2>Books</h2>
<table class="table table-striped">
	<tr><td></td><td>Title</td><td>Opinion</td></tr>
	<% @books.each do |book| %>
	<tr><td><%= attachment_image_tag @user, :profile_image, :fill,50,50,format:"jpeg",fallback: "no_image.jpg"  %></td>
		<td><%= link_to (book.title),book_path(book.id) %></td>
		<td><%= book.body %></td></tr>
	<% end %>
</table>
</div>